from __future__ import annotations

import json
from typing import Any


GRAPH: dict[str, Any] = json.loads('{"edges": [{"id": "e1", "source": "start_1", "target": "input_1"}, {"id": "e2", "source": "input_1", "target": "intent_1"}, {"id": "e3", "source": "intent_1", "target": "branch_1"}, {"id": "e4", "source": "branch_1", "target": "message_refund"}, {"id": "e5", "source": "branch_1", "target": "message_other"}, {"id": "e6", "source": "message_refund", "target": "output_1"}, {"id": "e7", "source": "message_other", "target": "output_1"}, {"id": "e8", "source": "output_1", "target": "end_1"}], "nodes": [{"config": {}, "enabled": true, "id": "start_1", "name": "start", "position": {"x": 80.0, "y": 160.0}, "type": "start"}, {"config": {"fields": [{"name": "user_query", "required": true, "type": "string"}]}, "enabled": true, "id": "input_1", "name": "input", "position": {"x": 260.0, "y": 160.0}, "type": "input"}, {"config": {"fallback_intent": "other", "intents": [{"description": "refund billing payment invoice", "name": "refund"}, {"description": "sales pricing quote purchase", "name": "sales"}], "model": "local-keyword", "provider": "keyword", "query": "{{input.user_query}}"}, "enabled": true, "id": "intent_1", "name": "intent", "output_mapping": {"confidence": "variables.intent_confidence", "intent": "variables.intent"}, "position": {"x": 440.0, "y": 160.0}, "type": "intent"}, {"config": {"branches": [{"condition": {"left": "{{variables.intent}}", "operator": "eq", "right": "refund"}, "id": "refund_path", "target": "message_refund"}, {"condition": true, "id": "fallback_path", "target": "message_other"}]}, "enabled": true, "id": "branch_1", "name": "branch", "position": {"x": 620.0, "y": 160.0}, "type": "branch"}, {"config": {"message_type": "text", "template": "refund branch handled {{input.user_query}}"}, "enabled": true, "id": "message_refund", "name": "message", "output_mapping": {"message": "variables.branch_message"}, "position": {"x": 800.0, "y": 160.0}, "type": "message"}, {"config": {"message_type": "text", "template": "fallback branch handled {{input.user_query}}"}, "enabled": true, "id": "message_other", "name": "message", "output_mapping": {"message": "variables.branch_message"}, "position": {"x": 800.0, "y": 160.0}, "type": "message"}, {"config": {"outputs": {"branch_message": "{{variables.branch_message}}", "confidence": "{{variables.intent_confidence}}", "intent": "{{variables.intent}}", "path": "{{path}}"}}, "enabled": true, "id": "output_1", "name": "output", "position": {"x": 980.0, "y": 160.0}, "type": "output"}, {"config": {}, "enabled": true, "id": "end_1", "name": "end", "position": {"x": 1160.0, "y": 160.0}, "type": "end"}], "schema_version": "1.0"}')


async def run(input_data: dict[str, Any], context) -> dict[str, Any]:
    return await context.execute_graph(GRAPH, input_data)
