from __future__ import annotations

import json
from typing import Any


GRAPH: dict[str, Any] = json.loads('{"edges": [{"id": "e1", "source": "start_1", "target": "input_1"}, {"id": "e2", "source": "input_1", "target": "api_1"}, {"id": "e3", "source": "api_1", "target": "message_1"}, {"id": "e4", "source": "message_1", "target": "output_1"}, {"id": "e5", "source": "output_1", "target": "end_1"}], "nodes": [{"config": {}, "enabled": true, "id": "start_1", "name": "start", "position": {"x": 80.0, "y": 160.0}, "type": "start"}, {"config": {"fields": [{"name": "user_query", "required": true, "type": "string"}, {"name": "customer_id", "required": true, "type": "string"}]}, "enabled": true, "id": "input_1", "name": "input", "position": {"x": 260.0, "y": 160.0}, "type": "input"}, {"config": {"body": {"customer": "{{input.customer_id}}", "query": "{{input.user_query}}", "source": "smoke"}, "headers": {"Authorization": "Bearer {{secrets.smoke_api_token_6fc5ccb1}}", "X-Smoke-Run": "{{input.customer_id}}"}, "method": "POST", "mock_response": {"customer": "{{input.customer_id}}", "summary": "created for {{input.user_query}}", "ticket_id": "SMK-{{input.customer_id}}"}, "mock_status_code": 202, "mode": "mock", "url": "https://api.example.test/tickets"}, "enabled": true, "id": "api_1", "name": "api", "output_mapping": {"response": "variables.api_response", "status": "variables.api_status"}, "position": {"x": 440.0, "y": 160.0}, "type": "api"}, {"config": {"message_type": "text", "template": "Ticket {{variables.api_response.ticket_id}} for {{variables.api_response.customer}}: {{input.user_query}}"}, "enabled": true, "id": "message_1", "name": "message", "output_mapping": {"message": "variables.message_text"}, "position": {"x": 620.0, "y": 160.0}, "type": "message"}, {"config": {"outputs": {"api_authorization_header": "{{outputs.api_1.request.headers.Authorization}}", "api_request_body": "{{outputs.api_1.request.body}}", "api_status": "{{variables.api_status}}", "message": "{{variables.message_text}}", "ticket_id": "{{variables.api_response.ticket_id}}"}}, "enabled": true, "id": "output_1", "name": "output", "position": {"x": 800.0, "y": 160.0}, "type": "output"}, {"config": {}, "enabled": true, "id": "end_1", "name": "end", "position": {"x": 980.0, "y": 160.0}, "type": "end"}], "schema_version": "1.0"}')


async def run(input_data: dict[str, Any], context) -> dict[str, Any]:
    return await context.execute_graph(GRAPH, input_data)
